version: "3"
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - pipeline_network

  db:
    image: mariadb:10.6
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: devops
      MYSQL_USER: devops_user
      MYSQL_PASSWORD: devops_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pipeline_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pipeline_network
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - pipeline_network
    restart: always

volumes:
  db_data:

networks:
  pipeline_network:
    driver: bridge
