version: "3.8"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db
      - jenkins
    networks:
      - pipeline_network

  db:
    image: mariadb:10.6
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: devops
      MYSQL_USER: devops_user
      MYSQL_PASSWORD: devops_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pipeline_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - pipeline_network
    environment:
      - DOCKER_HOST=tcp://docker:2375
    entrypoint: |
      /bin/bash -c "
        apt-get update && apt-get install -y \
        curl \
        python3-pip \
        && curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose \
        && chmod +x /usr/local/bin/docker-compose && \
        /usr/local/bin/jenkins.sh
      "

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pipeline_network
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - pipeline_network
    restart: always

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "devops_user:devops_password@tcp(db:3306)/"
    networks:
      - pipeline_network

volumes:
  db_data:
  jenkins_home:

networks:
  pipeline_network:
    driver: bridge
