global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "web"
    static_configs:
      - targets: ["web:5000"]

  - job_name: "db"
    static_configs:
      - targets: ["db:3307"]

  - job_name: "mysql-exporter"
    static_configs:
      - targets: ["mysql-exporter:9104"]
